name: shuttle-gh-cd
run-name: ${{ github.actor }} triggered shuttle deploy.

on:
    push:
        branches:
            - main
            - feature/gh-actions

jobs:
    start:
        runs-on: ubuntu-22.04
        steps:
            - name: Start release process
              run: echo "Starting release process to shuttle.rs"

            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                # Version Spec of the version to use in SemVer notation.
                # It also emits such aliases as lts, latest, nightly and canary builds
                # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
                node-version: '22.x'

            - uses: pnpm/action-setup@v4
              with:
                version: 9

            - run: node -v
            - run: pnpm -v