name: shuttle-gh-cd
run-name: ${{ github.actor }} triggered shuttle deploy.

on:
    push:
        branches:
            - main
            - feature/gh-actions

jobs:
    start:
        runs-on: ubuntu-22.04
        steps:
            - name: Start release process
              run: echo "Starting release process to shuttle.rs"